
# Section 2


## GIS methods

Here is some additional text and we can also reference a table (see table \ref{Ta:a_table}).  The incivility was the sum of features present within a block @costa_case_2017.

\begin{table}
\begin{center}
\caption{NIfETy Incivility Items}
\begin{tabular}{cc}
  \hline \\
Total Broken Windows &People Swearing \\
Eviction Signs &People in Physical Fights \\
Un-Boarded Abandoned Buildings  &People Loitering \\
Boarded Abandoned Buildings &Intoxicated People \\
Structures with Broken Windows &Evidence of Prostitution \\
\multicolumn{2}{c}{Memorials}\\ \\
  \hline
\end{tabular}
\label{Ta:a_table}
\end{center}
\end{table}

The geocoded Nifety data was read into R and used to develop a spatial prediction model (described in next section).  The predicted values and variances from these models were imported back into ArcGIS as a raster dataset
The centroid of each street segment was calculated and the raster with predicted incivilities was joined with the centroids (@costa_bayesian_2018).  Using a unique identifier, the centroids were rejoined to the street segments.  For blocks on which NIfETy data was collected, the block quality was the actual observed incivility value. For unsampled blocks the block quality was defined as the predicted value at the street centroid.

Next, the MORE data for the children and schools was geocoded. 340 of the children's home addresses were geocoded automatically and another 22 were manually geocoded. Two of the remaining records had no information on the school and were removed. The address could not be geocoded for the last remaining record.

Finally, the MORE data with the attached path qualities was joined to the NSA data so that neighborhood level effects could be included in the final models.  This complete dataset was exported from ArcGIS to R for analysis.

\subsection*{Predicting Incivilities}

The incivilities score for missing blocks was predicted using an ordinary kriging model.  Ordinary kriging is an method for optimal prediction of spatially continuous processes which assumes a constant, unknown mean.  For our case we consider points $\mathbf{z}=(z(s_{1}), \ldots,z(s_{n}))$ where $n$ is the total number of sampled spatial locations and the $s_{i},\, i=1,\ldots,n$ are an index of the spatial locations for the sampled points. Each $z(s)$ is an observed value of $\{Z(s):s\in D\}$, which is a random process that varies continuously throughout the region $D \subset \mathbb{R}^{2}$ according to the spatial index, $s$

As in regular regression, we want to estimate 'large scale'/trend effects and small scale 'variance/covariance' effects.  With just one observation from a joint probability dist and no assumptions, inference is not possible, since we need to estimate a potentially different mean for each location in addition to different covariance between any two locations. Therefore, we formulate a model and specify several assumptions which allow us estimate the model parameters. A process is (second order) stationary if the conditions below are met:
\begin{gather}
E(Z(s))=\mu(s)=\mu,\text{for all }s \in D (\#eq:eq2-1)\\
Var(Z(s))=\sigma^{2}(s)=\sigma^{2},\text{for all }s \in D (\#eq:eq2-2)\\
Cov(Z(s_{1}),Z(s_{2}))=C(s_{i}-s_{j}),\text{for all }s_{i}\ne s_{j} \in D (\#eq:eq2-3)
\end{gather}
Equations \@ref(eq:eq2-1) and \@ref(eq:eq2-2) ensure that the mean and variance are constant and independent of location throughout the region $D$. Equation \@ref(eq:eq2-3) ensures that the covariance depends only on the difference between two locations, rather than the locations themselves. $C(\cdot)$ in equation \@ref(eq:eq2-3) is called the covariance function.

Another possible assumption related to the variability between points is
\begin{equation}
  Var(Z(s_{1})-Z(s_{2}))=2\gamma(s_{i}-s_{j}),\text{for all }s_{i}\ne s_{j} \in D (\#eq:eq2-4)
\end{equation}
$2\gamma(\cdot)$ is called the variogram function and $\gamma(\cdot)$ is the semivariogram.

A more general form of stationarity called intrinsic stationary is equivalent to accepting the assumptions in equations \@ref(eq:eq2-1),\@ref(eq:eq2-2) and \@ref(eq:eq2-4). The form of stationarity chosen for model will determine which of equation \@ref(eq:eq2-3) or \@ref(eq:eq2-4) is used to model spatial dependence between points.  Since the intrinsic stationarity assumption is more general and because the variogram and semivariogram have been shown to be more robust than the covariogram (citation) we will work with the semivariogram.

A further assumption called isotropy replaces the difference vectors $(s_{i}-s_{j})$ with $||s_{i}-s_{j}||=\mathbf{h}$ and assumes that that covariogram or variogram are functions of distance alone rather than distance and direction.

Plotting the values of the semivariogram against the distances for all pairs of locations, $\mathbf{h}$ gives a plot called the variogram cloud.
(empirical variogram)
\begin{gather*}
\hat{\gamma}(\mathbf{h})=\frac{1}{2|N(\mathbf{h})|}\sum_{N(\mathbf{h})}(Z(s_{i})-Z(s_{j}))^{2}
\end{gather*}
Where $\mathbf{h}$ indexes each class ($\mathbf{h}$ is often the midpoint of each class range), $N(\mathbf{h})$ is the set of all points within the class,  $|N(\mathbf{h})|$ is the number of points within the class. By collecting the points within classes and then taking the average within each class we produce the empirical semivariogram estimator.

The empirical semivariogram is useful to explore the spatial dependence in the data, however in order to estimate values with the ordinary kriging equation, we must have a model for the `true' variogram.  Several families of variogram model have been validated and are considered (@smith_bayesian_nodate, @biswas_bayesian_2009).  To fit the model we rely on least squares methods which fit the model to the empirical semivariogram.
 
We begin the kriging process by importing the geocoded NIfETy data into R.  We use the R package ``copula" @hofert_copula:_2016. A map of NIfETy sample locations and incivility values was produced to visually examine spatial dependence. Next the variogram cloud, classical empirical semivariogram estimator, and robust semivariogram estimator were plotted and compared.  Anisotropy was explored using directional semivariograms and an empirical semivariogram contour map.

